// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-FZkZ0Qrvz3I-pVP3h--9L8ddtq-izb8',
    appId: '1:995516789253:web:76e01e566477360a07626c',
    messagingSenderId: '995516789253',
    projectId: 'flutte-auth-d249d',
    authDomain: 'flutte-auth-d249d.firebaseapp.com',
    storageBucket: 'flutte-auth-d249d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCniiPNgy5vE6JJzDi3KVwoRmd_KJIAkDg',
    appId: '1:995516789253:android:203df10f26f77fc607626c',
    messagingSenderId: '995516789253',
    projectId: 'flutte-auth-d249d',
    storageBucket: 'flutte-auth-d249d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBYeH4WKnTaquD4dsWvPvE6krB0EEz544',
    appId: '1:995516789253:ios:099f65f59461695d07626c',
    messagingSenderId: '995516789253',
    projectId: 'flutte-auth-d249d',
    storageBucket: 'flutte-auth-d249d.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBYeH4WKnTaquD4dsWvPvE6krB0EEz544',
    appId: '1:995516789253:ios:099f65f59461695d07626c',
    messagingSenderId: '995516789253',
    projectId: 'flutte-auth-d249d',
    storageBucket: 'flutte-auth-d249d.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-FZkZ0Qrvz3I-pVP3h--9L8ddtq-izb8',
    appId: '1:995516789253:web:dd684389166eb2dc07626c',
    messagingSenderId: '995516789253',
    projectId: 'flutte-auth-d249d',
    authDomain: 'flutte-auth-d249d.firebaseapp.com',
    storageBucket: 'flutte-auth-d249d.firebasestorage.app',
  );
}
